<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CA1311;CA1304;CA1873;CA1861;CA1725;CA1822;CA1848;CA1847</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FashionStore.UnitTests" />
  </ItemGroup>


  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FashionStore.Domain\FashionStore.Domain.csproj" />
    <ProjectReference Include="..\FashionStore.Application\FashionStore.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

</Project>
